### ISSUE TITLE
TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems' when using lce.convert_keras_model with INT8 quantization

### ISSUE THREAD

**Issue by Ridam2k** [larq/larq#913]
### Describe the bug
When attempting to convert a Larq model to INT8 quantized TFLite format using lce.convert_keras_model() with inference_input_type=tf.int8 and inference_output_type=tf.int8, the conversion fails with a TypeError related to FlatBuffers vector construction.

### To Reproduce

Min. reproducible code

import tensorflow as tf
import larq_compute_engine as lce

### Assuming 'model' is a trained Larq Keras model like Quicknet
```
tflite_model = lce.convert_keras_model(
    model, 
    inference_input_type=tf.int8, 
    inference_output_type=tf.int8, 
    experimental_default_int8_range=(-0.1, 1.1)
)

with open("model_int8.tflite", "wb") as f:
    f.write(tflite_model)
```

### Error Traceback
```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_2295851/1787395782.py in <cell line: 2>()
      1 ### INT 8 conversion storage ####
----> 2 tflite_model = lce.convert_keras_model(model, inference_input_type=tf.int8, inference_output_type=tf.int8, experimental_default_int8_range=(0, 4))
      3 
      4 with open("wr-quicknet-small-5class-3-1-INT8.tflite", "wb") as f:
      5     f.write(tflite_model)

~/anaconda3/envs/larq/lib/python3.8/site-packages/larq_compute_engine/mlir/python/converter.py in convert_keras_model(model, inference_input_type, inference_output_type, target, experimental_default_int8_range)
    281         inference_input_type != tf.float32 or inference_output_type != tf.float32
    282     ):
--> 283         tflite_buffer = modify_integer_quantized_model_io_type(
    284             tflite_buffer,
    285             inference_input_type=inference_input_type,

~/anaconda3/envs/larq/lib/python3.8/site-packages/larq_compute_engine/mlir/python/util.py in modify_integer_quantized_model_io_type(model, inference_input_type, inference_output_type)
    220 
    221     # Convert the model to a bytearray
--> 222     return _convert_model_from_object_to_bytearray(model)
    223 
    224 

~/anaconda3/envs/larq/lib/python3.8/site-packages/larq_compute_engine/mlir/python/util.py in _convert_model_from_object_to_bytearray(model_object)
     50     # Initial size of the buffer, which will grow automatically if needed
     51     builder = flatbuffers.Builder(1024)
---> 52     model_offset = model_object.Pack(builder)
     53     builder.Finish(model_offset, file_identifier=_TFLITE_FILE_IDENTIFIER)
     54     return bytes(builder.Output())

~/anaconda3/envs/larq/lib/python3.8/site-packages/larq_compute_engine/mlir/python/tflite_schema.py in Pack(self, builder)
  12145             for i in reversed(range(len(self.operatorCodes))):
  12146                 builder.PrependUOffsetTRelative(operatorCodeslist[i])
> 12147             operatorCodes = builder.EndVector()
  12148         if self.subgraphs is not None:
  12149             subgraphslist = []

TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems'
```

### Expected behavior
The model should be successfully converted to the quantized TFLite format without errors

### Environment

TensorFlow version: 2.5.0
Larq version: 0.13.3
LCE version: 0.11.1
Numpy: 1.19.5
Python: 3.8.0
OS: Linux

#### Additional Context

1. Model Architecture: The model is a Larq binary neural network (Quicknet) with mixed precision (binary + FP32 layers)

2. Conversion Target: Attempting to convert to INT8 input/output for deployment on edge devices

3. Range Values Tested:

   - `(-0.1, 1.1)` - failed
   - `(0, 4)` - failed

4. Working Alternative: Conversion works fine without the experimental_default_int8_range:\

`tflite_model = lce.convert_keras_model(model, inference_input_type=tf.int8, inference_output_type=tf.int8)`

**Comment by Tombana** [comment]
Thank you for reporting this issue.

This has to do with the version of the `flatbuffers` Python package, it seems we have not pinned the version properly. I'm not entirely sure if you need a newer, or an older version. Could you try to update `flatbuffers` to the latest version? If that doesn't work, try using `flatbuffers==2.0`.

**Comment by Ridam2k** [comment]
Thank you for getting back - it indeed seems to be a flatbuffers version issue, it works fine with version `flatbuffers==2.0` !
